name=input('what is your name?')
food=input('what is your favourite food?')
music=input('what is your favourite music?')
place=input('where do you live?')
print('you are' ,name)
print('you"re probably hungry for',food)
print('and you"re definitely getting your groove on to', music)
print('living in the amazing',place)